# Generated by Django 6.0.4 on 2026-04-16 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du logiciel')),
                ('url_acces', models.URLField(verbose_name="Lien d'accès")),
                ('icone_name', models.CharField(default='box', help_text="Nom de l'icône Lucide (ex: box, activity, users)", max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='DirectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.application')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.direction')),
            ],
            options={
                'verbose_name': 'Habilitation',
                'verbose_name_plural': 'Habilitations',
                'unique_together': {('direction', 'application')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='directions_autorisees',
            field=models.ManyToManyField(related_name='applications', through='catalogue.DirectionApplication', to='organizations.direction'),
        ),
    ]
