# Generated by Django 6.0.4 on 2026-04-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivite',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Adresse IP'),
        ),
    ]
